# Generated by Django 2.2.7 on 2019-11-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20191116_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
