# Generated by Django 2.2.7 on 2019-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_deleted', models.BooleanField(verbose_name='Deleted')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('updated_by', models.CharField(max_length=20, verbose_name='Updated By')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
            ],
        ),
    ]
