# Generated by Django 2.2.7 on 2019-11-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('snooze', models.DateTimeField(auto_now_add=True, verbose_name='Snooze')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('conn_str', models.CharField(max_length=20, verbose_name='Connection String')),
                ('comments', models.TextField(max_length=200, verbose_name='Comments')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Domain')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
