# Generated by Django 2.2.7 on 2019-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Active'),
        ),
    ]
