# Generated by Django 2.2.7 on 2019-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20191127_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='server',
            name='application',
            field=models.ManyToManyField(null=True, to='server.Application', verbose_name='Aplications'),
        ),
    ]
