# Generated by Django 2.2.7 on 2019-11-18 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_remove_property_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0001_initial'),
        ('server', '0004_auto_20191117_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('snooze', models.DateTimeField(auto_now_add=True, verbose_name='Snooze')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('conn_str', models.CharField(max_length=20, verbose_name='Connection String')),
                ('comments', models.TextField(max_length=200, verbose_name='Comments')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
