# Generated by Django 2.2.7 on 2019-12-10 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0004_auto_20191127_1441'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='application',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='domain',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='property',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='server',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='conn_str',
        ),
        migrations.RemoveField(
            model_name='server',
            name='snooze',
        ),
        migrations.AlterField(
            model_name='server',
            name='application',
            field=models.ManyToManyField(null=True, to='server.Application', verbose_name='Applications'),
        ),
        migrations.CreateModel(
            name='LoginProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('login', models.CharField(max_length=20, verbose_name='Login')),
                ('passwd', models.CharField(max_length=50, verbose_name='Password')),
                ('comments', models.TextField(max_length=200, verbose_name='Comments')),
                ('is_active', models.BooleanField(default=1, verbose_name='Active')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Update On')),
                ('inserted_on', models.DateTimeField(auto_now_add=True, verbose_name='Inserted On')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
            options={
                'verbose_name': 'Login Profile',
                'verbose_name_plural': 'Login Profiles',
                'ordering': ['name'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='login_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.LoginProfile', verbose_name='Login Profile'),
        ),
    ]
