# Generated by Django 2.2.7 on 2019-12-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191210_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginprofile',
            name='is_active',
        ),
    ]
