# Generated by Django 2.2.7 on 2019-11-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_deleted',
        ),
    ]
